### ISSUE TITLE
Docker container?

### ISSUE THREAD

**Issue by robigan** [Shinmera/ldapper#1]
Please 🙏

**Comment by Shinmera** [comment]
I've never used docker, so I'm of little help here

**Comment by robigan** [comment]
oof, I'll see what I can do one of these days

**Comment by winks** [comment]
Same problem here, this is WIP:

```
FROM debian:12

RUN \
        apt-get update && \
        apt-get upgrade && \
        apt-get install -y sbcl curl gcc
RUN \
        cd /tmp && \
        curl -O https://beta.quicklisp.org/quicklisp.lisp && \
        sbcl --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' && \
        echo '#-quicklisp\n(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp"\n  (user-homedir-pathname))))\n      (when (probe-file quicklisp-init)\n        (load quicklisp-init)))' > /root/.sbclrc
```
then continue with the instructions from https://github.com/Shinmera/ldapper/blob/master/.github/workflows/build.yml#L30

**Comment by Shinmera** [comment]
Instead of that `&& echo` you can use add `--eval '(let ((ql:*do-not-prompt* T)) (ql:add-to-init-file))'`

**Comment by Shinmera** [comment]
Instead of manually installing sbcl and quicklisp like this, you should also be able to use `roswell`, which seems to have a docker image to use already, too.

**Comment by winks** [comment]
ah the without prompting was exactly the problem, thanks :)

happy to convert this to a proper PR in the next days

**Comment by winks** [comment]
> Instead of manually installing sbcl and quicklisp like this, you should also be able to use `roswell`, which seems to have a docker image to use already, too.

Yeah I had actually already written half of it when I looked for the details in your action and I|d never even heard of roswell.

**Comment by Shinmera** [comment]
With #2 there's some instructions on how to get this dockerized now.
